version: 2

workflows:
  version: 2
  test:
    jobs:
      - openjdk7
      - openjdk8

jobs:
  openjdk7:
    docker:
      - image: azul/zulu-openjdk-alpine:7
    steps:
      - checkout

      - run:
         name: install openjdk 7
         command: |
           apk add maven
           apk add zip
           export M2_HOME=~/.m2
           export MAVEN_HOME=~/.m2
           export MAVEN_OPTS=-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

      - restore_cache:
          key: circleci-wovnjava-openjdk-pom-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-wovnjava-openjdk-pom-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Collect artifacts
          command: |
            mkdir target/artifacts
            version=`grep '^    <version>' pom.xml | sed -e 's/    <version>//' | sed -e 's!</version>!!'`
            zip target/wovnjava-jar-${version}.zip -jr target/wovnjava-*.jar licenses/*
            mv target/wovnjava-* target/artifacts

      - store_artifacts:
          path: target/artifacts/


  openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - restore_cache:
          key: circleci-wovnjava-openjdk-pom-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-wovnjava-openjdk-pom-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Collect artifacts
          command: |
            mkdir target/artifacts
            version=`grep '^    <version>' pom.xml | sed -e 's/    <version>//' | sed -e 's!</version>!!'`
            zip target/wovnjava-jar-${version}.zip -jr target/wovnjava-*.jar licenses/*
            mv target/wovnjava-* target/artifacts

      - store_artifacts:
          path: target/artifacts/
